# Site settings
title: Blog Red Ciudadana
email: info@redciudadana.org
description: > # Writer Theme is a responsive template
 Somos una organización sin fines de lucro, creada con la misión de incentivar la participación y auditoría ciudadana.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.redciudadana.org/" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/michelle', 'fa-user']
single_footer: '<p>The writer community loves your content. Writer &copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Writer 2016', '/about']


# Build settings
# markdown: kramdown
